AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rad

  Sample SAM Template for rad

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - local
      - dev
      - build
      - staging
      - integration
      - prod
  CommitHash:
    Type: String
    Default: COMMITHASHTOREPLACE
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"


Conditions:
  NonProd: !Not [!Equals [!Ref Environment, prod]]
  CodeSigningEnabled:
    Fn::Not:
      - Fn::Or:
          - Fn::Equals:
            - Environment
            - local
          - Fn::Equals:
            - Environment
            - dev
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"


Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Architectures:
      - arm64
    CodeSigningConfigArn: !If
      - CodeSigningEnabled
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Environment:
      Variables:
        ASSET_PATH: !Sub "https://${AssetDistribution.DomainName}/${CommitHash}"
        SESSION_TABLE: !Ref SessionTable
        DYNAMO_DB_ENDPOINT_OVERRIDE: ""
        ENVIRONMENT: !Ref Environment
  Api:
    TracingEnabled: true

Resources:
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
  AssetBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            - Action:
              - 's3:GetObject'
              Effect: Allow
              Resource: !Sub "${AssetBucket.Arn}/*"
              Principal:
                Service: "cloudfront.amazonaws.com"
              Condition:
                StringEquals:
                  "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${AssetDistribution}"
  AssetDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Origins:
          - DomainName: !GetAtt AssetBucket.RegionalDomainName
            Id: s3-assets
            OriginAccessControlId: !GetAtt AssetDistributionOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Cache disabled managed policy
          ViewerProtocolPolicy: https-only
          TargetOriginId: s3-assets
  AssetDistributionOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: s3-assets
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Variables:
        Environment: !Ref Environment
      Auth:
        DefaultAuthorizer: !Ref Environment
        Authorizers:
          dev:
            FunctionArn: !GetAtt NonProdAuthoriserFunction.Arn
            FunctionPayloadType: TOKEN
          build:
            FunctionArn: !GetAtt NonProdAuthoriserFunction.Arn
            FunctionPayloadType: TOKEN
          staging:
            FunctionArn: !GetAtt NonProdAuthoriserFunction.Arn
            FunctionPayloadType: TOKEN
          integration:
            FunctionArn: !GetAtt NonProdAuthoriserFunction.Arn
            FunctionPayloadType: TOKEN
          prod:
            FunctionArn: !GetAtt ProdAuthoriserFunction.Arn
            FunctionPayloadType: REQUEST
            Identity:
              StageVariables:
                - Environment
          local:
            FunctionArn: !GetAtt ProdAuthoriserFunction.Arn
            FunctionPayloadType: REQUEST
            Identity:
              StageVariables:
                - Environment
      Domain:
        DomainName: report-a-death.dev.account.gov.uk
        CertificateArn:
          Fn::ImportValue: CertificateArn
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId:
            Fn::ImportValue: HostedZoneId
          EvaluateTargetHealth: true
          IpV6: true

  NonProdAuthoriserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/authoriser/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  ProdAuthoriserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/prod-authoriser/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  UnauthorizedErrorResponse:
    Condition: NonProd
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: UNAUTHORIZED
      ResponseParameters:
        "gatewayresponse.header.WWW-Authenticate": "'Basic'"
      StatusCode: "401"


  4xxErrorResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: DEFAULT_4XX
      ResponseTemplates:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'gateway-error.yaml'

  5xxErrorResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: DEFAULT_5XX
      ResponseTemplates:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'gateway-error.yaml'

  StartFunction:
    Type: AWS::Serverless::Function
    Connectors:
      SessionTable:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: src/pages/start/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        EntryPoints:
          - app.ts
  DemoFunction:
    Type: AWS::Serverless::Function
    Connectors:
      SessionTable:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: src/pages/demo/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /demo
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /demo
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        External:
        - "@aws-sdk/client-dynamodb"
        - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        EntryPoints:
        - app.ts

  CheckAnswersFunction:
    Type: AWS::Serverless::Function
    Connectors:
      SessionTable:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: src/pages/check-answers/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /check-answers
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /check-answers
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        EntryPoints:
          - app.ts

  SubmittedFunction:
    Type: AWS::Serverless::Function
    Connectors:
      SessionTable:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Read
    Properties:
      CodeUri: src/pages/submitted/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submitted
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
        Sourcemap: true
        EntryPoints:
          - app.ts

  NoSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/pages/no-session/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /error/no-session
            Method: any
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  NotFoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/pages/not-found/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: any
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  AssetBucketName:
    Value: !Ref AssetBucket