version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    working_dir: /home/dynamodblocal
    ports:
      - 8000:8000
    container_name: dynamodb-local
    networks:
      - lambda-local

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: unless-stopped
    networks:
      - lambda-local

  dynamodb_migrator:
    image: amazon/aws-cli
    container_name: app-dynamodb_migrator
    working_dir: /tmp
    command: dynamodb create-table --cli-input-json file://create-table.json --endpoint-url http://dynamodb-local:8000
    volumes:
      - .:/tmp:rw
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      AWS_DEFAULT_REGION: eu-west-2
    depends_on:
      - dynamodb-local
    networks:
      - lambda-local

networks:
  lambda-local:
    name: lambda-local
    attachable: true