name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Set commit hash
        run: sed -i s/\${CommitHash}/${{ github.sha }}/g template.yaml gateway-error.yaml
      - run: make
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ASSET_ROLE_ARN }}
          role-session-name: upload-assets
          aws-region: "eu-west-2"
      - name: Upload static assets
        run: |
          aws s3 cp --recursive assets/public "s3://${{ secrets.ASSET_BUCKET_NAME }}/${{ github.sha }}"
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          role-session-name: deploy-sam
          aws-region: "eu-west-2"
      - uses: alphagov/di-devplatform-upload-action@v3.3
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: .aws-sam/build